//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagining.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthWindEntities : DbContext
    {
        public NorthWindEntities()
            : base("name=NorthWindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("NorthWindEntities", "pagining")]
        public virtual IQueryable<pagining_Result> pagining(Nullable<int> pagina, Nullable<int> cantidadregistros)
        {
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("pagina", pagina) :
                new ObjectParameter("pagina", typeof(int));
    
            var cantidadregistrosParameter = cantidadregistros.HasValue ?
                new ObjectParameter("cantidadregistros", cantidadregistros) :
                new ObjectParameter("cantidadregistros", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<pagining_Result>("[NorthWindEntities].[pagining](@pagina, @cantidadregistros)", paginaParameter, cantidadregistrosParameter);
        }
    }
}
